server:
  host: localhost
  port: 8080
  read_timeout: 30
  write_timeout: 30

database:
  type: memory
  host: localhost
  port: 5432
  name: automation_hub
  user: postgres
  password: ""
  ssl_mode: disable

logging:
  level: info
  format: json
