version: '3.8'

services:
  backend:
    build: .
    container_name: aura-core-backend
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://aura_user:aura_password@db:5432/aura_db
      - PORT=4000
      - JWT_SECRET=your-super-secret-jwt-key
      - FRONTEND_URL=http://localhost:3000
    networks:
      - aura-network

  db:
    image: postgres:14-alpine
    container_name: aura-core-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=aura_user
      - POSTGRES_PASSWORD=aura_password
      - POSTGRES_DB=aura_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - aura-network
    
volumes:
  postgres-data:

networks:
  aura-network:
    driver: bridge