version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: bankhub_postgres
    environment:
      POSTGRES_DB: bankhub
      POSTGRES_USER: bankhub_user
      POSTGRES_PASSWORD: bankhub_secure_password_2024
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/postgresql_schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    networks:
      - bankhub_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bankhub_user -d bankhub"]
      interval: 30s
      timeout: 10s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: bankhub_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@bankhub.local
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - bankhub_network
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  bankhub_network:
    driver: bridge
